M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Wed 18 Oct 2023 17:56:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-18T17:56:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X88.57Y-163.5
X89.84Y-115.24
X140.64Y-130.48
X140.64Y-158.42
T0
M30
